version: '3.9'
services:
   backend:
        build:
          context: ./server
          dockerfile: Dockerfile
        image: server/app:1
        container_name: server
        ports:
          - "5000:5000"
        networks:
          - mern-app
   frontend:
        build: 
          context: ./client
          dockerfile: Dockerfile
        image: client/app:1
        container_name: client
        stdin_open: true
        command: npm start
        ports:
          - "3000:3000"
        networks:
          - mern-app
networks:
  mern-app:
       driver: bridge
